#!/usr/bin/env python3
"""render.py — deterministic renderer: config + assets -> generated toolkit files.

Part 1 (this section): a tiny frozen template engine.
Dialect (FROZEN — do not extend):
  {{path.to.value}}                    variable substitution (dot-path into context)
  {{#if expr}}...{{else}}...{{/if}}    expr = dot-path truthiness, or  path == "lit" / path != "lit"
  {{#unless expr}}...{{/unless}}
  {{#each path}}...{{this.key}}...{{/each}}   iterate a list; item bound to `this`
Blocks may nest. A missing dot-path (typo) raises TemplateError from a bare
{{var}} (fail loudly at init time); an explicit null value at an existing
path renders as an empty string instead. {{#each}} treats a missing path,
an explicit null, and a non-list value alike as zero iterations.
Exit codes (CLI, part 2): 0 success / 1 conflicts or config validation failure / 2 usage error.
"""
import sys

if sys.version_info < (3, 9):
    sys.stderr.write("error: superrelease scripts require Python 3.9+\n")
    sys.exit(2)

import argparse
import json
import re
import stat
import subprocess
from datetime import datetime, timezone
from pathlib import Path

TAG_RE = re.compile(r"\{\{(.*?)\}\}")
COND_RE = re.compile(r'^(\S+)\s*(==|!=)\s*"([^"]*)"$')
MARKER_RE = re.compile(r"generated by superrelease v(\d+\.\d+\.\d+)")

_MISSING = object()


class TemplateError(ValueError):
    pass


def tokenize(text):
    tokens, pos = [], 0
    for m in TAG_RE.finditer(text):
        if m.start() > pos:
            tokens.append(("text", text[pos:m.start()]))
        tokens.append(("tag", m.group(1).strip()))
        pos = m.end()
    if pos < len(text):
        tokens.append(("text", text[pos:]))
    return tokens


def parse(tokens):
    root = []
    stack = [("root", None, root)]
    for kind, value in tokens:
        current = stack[-1][2]
        if kind == "text":
            current.append({"kind": "text", "s": value})
        elif value.startswith("#if "):
            node = {"kind": "if", "cond": value[4:].strip(), "then": [], "else": []}
            current.append(node)
            stack.append(("if", node, node["then"]))
        elif value.startswith("#unless "):
            node = {"kind": "unless", "cond": value[8:].strip(), "body": []}
            current.append(node)
            stack.append(("unless", node, node["body"]))
        elif value.startswith("#each "):
            node = {"kind": "each", "path": value[6:].strip(), "body": []}
            current.append(node)
            stack.append(("each", node, node["body"]))
        elif value == "else":
            head, node, _ = stack[-1]
            if head != "if":
                raise TemplateError("{{else}} outside {{#if}}")
            stack[-1] = ("if", node, node["else"])
        elif value in ("/if", "/unless", "/each"):
            if len(stack) == 1:
                raise TemplateError("unexpected {{" + value + "}}")
            head, node, _ = stack.pop()
            if value != "/" + head:
                raise TemplateError("mismatched {{" + value + "}} closing {{#" + head + "}}")
        else:
            current.append({"kind": "var", "path": value})
    if len(stack) != 1:
        raise TemplateError("unclosed {{#" + stack[-1][0] + "}} block")
    return root


def lookup(ctx, dotted):
    cur = ctx
    for part in dotted.split("."):
        if isinstance(cur, dict) and part in cur:
            cur = cur[part]
        else:
            return _MISSING
    return cur


def truthy(ctx, expr):
    m = COND_RE.match(expr)
    if m:
        val = lookup(ctx, m.group(1))
        # A missing path never equals a literal (and therefore != is true).
        present = val is not _MISSING and val is not None
        eq = present and str(val) == m.group(3)
        return eq if m.group(2) == "==" else not eq
    val = lookup(ctx, expr)
    return False if val is _MISSING else bool(val)


def evaluate(nodes, ctx):
    out = []
    for n in nodes:
        kind = n["kind"]
        if kind == "text":
            out.append(n["s"])
        elif kind == "var":
            val = lookup(ctx, n["path"])
            if val is _MISSING:
                raise TemplateError("unknown placeholder: {{" + n["path"] + "}}")
            if val is None:
                out.append("")
            elif isinstance(val, str):
                out.append(val)
            else:
                out.append(json.dumps(val, ensure_ascii=False))
        elif kind == "if":
            branch = n["then"] if truthy(ctx, n["cond"]) else n["else"]
            out.append(evaluate(branch, ctx))
        elif kind == "unless":
            if not truthy(ctx, n["cond"]):
                out.append(evaluate(n["body"], ctx))
        elif kind == "each":
            items = lookup(ctx, n["path"])
            if not isinstance(items, list):
                items = []
            for item in items:
                sub = dict(ctx)
                sub["this"] = item
                out.append(evaluate(n["body"], sub))
    return "".join(out)


def render_template(text, ctx):
    return evaluate(parse(tokenize(text)), ctx)


# ---------------------------------------------------------------------------
# Part 2: manifest-driven file pipeline
# ---------------------------------------------------------------------------

MD_MARKER = ("<!-- generated by superrelease v{v} — do not edit; "
             "re-run init to regenerate (직접 수정하지 말고 재init 하세요) -->")
HASH_MARKER = "# generated by superrelease v{v} — do not edit; re-run init to regenerate"


def marker_for(dest_name, version):
    if dest_name.endswith(".md"):
        return MD_MARKER.format(v=version)
    return HASH_MARKER.format(v=version)


def insert_marker(content, dest_name, version):
    marker = marker_for(dest_name, version)
    if dest_name.endswith(".md") and content.startswith("---\n"):
        end = content.find("\n---\n", 4)
        if end != -1:
            at = end + len("\n---\n")
            return content[:at] + marker + "\n" + content[at:]
    if dest_name.endswith(".py") and content.startswith("#!"):
        nl = content.find("\n") + 1
        return content[:nl] + marker + "\n" + content[nl:]
    return marker + "\n" + content


def validate_config(config):
    problems = []
    sr = config.get("superrelease") or {}
    if not isinstance(sr.get("configVersion"), int):
        problems.append("superrelease.configVersion (int) is required")
    repo = config.get("repo") or {}
    for key in ("kind", "defaultBranch", "releasePath"):
        if not repo.get(key):
            problems.append("repo." + key + " is required")
    scopes = config.get("scopes")
    if not scopes:
        problems.append("scopes must be a non-empty list")
    else:
        for i, s in enumerate(scopes):
            for key in ("name", "path"):
                if not s.get(key):
                    problems.append("scopes[{}].{} is required".format(i, key))
            if not (s.get("scheme") or {}).get("type"):
                problems.append("scopes[{}].scheme.type is required".format(i))
            if not s.get("versionLocations"):
                problems.append("scopes[{}].versionLocations is required".format(i))
    strategy = repo.get("monorepoStrategy")
    if repo.get("kind") == "monorepo" and strategy not in ("fixed", "independent"):
        problems.append('repo.monorepoStrategy must be "fixed" or "independent" '
                        'when repo.kind is "monorepo"')
    if strategy == "independent" and scopes and len(scopes) < 2:
        problems.append("independent strategy requires at least two scopes")
    if strategy in ("fixed", "independent") and repo.get("kind") != "monorepo":
        problems.append('repo.monorepoStrategy is only valid when repo.kind is "monorepo"')
    return problems


def project_name(repo_dir):
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo_dir), "remote", "get-url", "origin"],
            capture_output=True, text=True)
        if proc.returncode == 0 and proc.stdout.strip():
            name = proc.stdout.strip().rstrip("/").rsplit("/", 1)[-1]
            return name[:-4] if name.endswith(".git") else name
    except FileNotFoundError:
        pass
    return Path(repo_dir).resolve().name


def build_context(config, repo_dir, plugin_version, now):
    ctx = dict(config)
    ctx["project"] = {"name": project_name(repo_dir)}
    ctx["plugin"] = {"version": plugin_version}
    ctx["generated"] = {"at": now}
    ctx["scope"] = (config.get("scopes") or [{}])[0]
    return ctx


def _normalized(text):
    return text.replace("\r\n", "\n")


def classify(entry, dest, new_content):
    if not dest.exists():
        return "create"
    existing = dest.read_text(encoding="utf-8")
    if MARKER_RE.search(existing):
        return "unchanged" if _normalized(existing) == _normalized(new_content) else "update"
    if entry.get("preserve") == "template":
        return "preserve"
    return "conflict"


def build_plan(manifest, assets_dir, repo_dir, ctx, plugin_version):
    plan = []
    for entry in manifest["entries"]:
        when = entry.get("when")
        if when and not truthy(ctx, when):
            plan.append((entry, "skipped", None))
            continue
        src = assets_dir / entry["src"]
        content = src.read_text(encoding="utf-8")
        if entry.get("render"):
            content = render_template(content, ctx)
        content = insert_marker(content, Path(entry["dest"]).name, plugin_version)
        plan.append((entry, classify(entry, repo_dir / entry["dest"], content), content))
    return plan


def apply_plan(plan, repo_dir, force):
    written = 0
    for entry, status, content in plan:
        if status in ("skipped", "preserve", "unchanged"):
            continue
        if status == "conflict" and not force:
            continue
        dest = repo_dir / entry["dest"]
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists():
            with open(dest, "r", encoding="utf-8", newline="") as f:
                if "\r\n" in f.read():
                    content = content.replace("\n", "\r\n")
        with open(dest, "w", encoding="utf-8", newline="") as f:
            f.write(content)
        if entry.get("executable"):
            dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        written += 1
    return written


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="render.py",
        description="Render superrelease assets into a target repo using config.json.")
    parser.add_argument("--config", required=True, help="path to .superrelease/config.json")
    parser.add_argument("--assets", required=True, help="plugin assets directory")
    parser.add_argument("--repo", required=True, help="target repository root")
    parser.add_argument("--check", action="store_true", help="report the plan; write nothing")
    parser.add_argument("--force", action="store_true", help="overwrite files without a marker")
    parser.add_argument("--now", help="ISO timestamp override for deterministic output")
    args = parser.parse_args(argv)

    config_path, assets_dir, repo_dir = Path(args.config), Path(args.assets), Path(args.repo)
    if not config_path.is_file():
        sys.stderr.write("error: config not found: " + str(config_path) + "\n")
        sys.exit(2)
    if not assets_dir.is_dir():
        sys.stderr.write("error: assets dir not found: " + str(assets_dir) + "\n")
        sys.exit(2)
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        sys.stderr.write("error: invalid config JSON: " + str(e) + "\n")
        sys.exit(1)
    problems = validate_config(config)
    if problems:
        for p in problems:
            sys.stderr.write("config: " + p + "\n")
        sys.exit(1)

    manifest_path = assets_dir / "manifest.json"
    if not manifest_path.is_file():
        sys.stderr.write("error: manifest not found: " + str(manifest_path) + "\n")
        sys.exit(2)
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        sys.stderr.write("error: invalid manifest JSON: " + str(e) + "\n")
        sys.exit(2)
    plugin_json = assets_dir.resolve().parents[2] / ".claude-plugin" / "plugin.json"
    if not plugin_json.is_file():
        sys.stderr.write("error: plugin.json not found: " + str(plugin_json) + "\n")
        sys.exit(2)
    plugin_version = json.loads(plugin_json.read_text(encoding="utf-8"))["version"]
    now = args.now or datetime.now(timezone.utc).isoformat(timespec="seconds")

    ctx = build_context(config, repo_dir, plugin_version, now)
    try:
        plan = build_plan(manifest, assets_dir, repo_dir, ctx, plugin_version)
    except TemplateError as e:
        sys.stderr.write("template error: " + str(e) + "\n")
        sys.exit(1)

    for entry, status, _ in plan:
        print("{:>9}  {}".format(status, entry["dest"]))
    conflicts = [e["dest"] for e, s, _ in plan if s == "conflict"]
    if conflicts and not args.force:
        sys.stderr.write("conflicts: files without a superrelease marker exist; "
                         "re-run with --force to overwrite\n")
        sys.exit(1)
    if args.check:
        sys.exit(0)
    written = apply_plan(plan, repo_dir, args.force)
    print("rendered {} file(s) into {}".format(written, repo_dir))


if __name__ == "__main__":
    main()
