#!/usr/bin/env python3
"""render.py — deterministic renderer: config + assets -> generated toolkit files.

Part 1 (this section): a tiny frozen template engine.
Dialect (FROZEN — do not extend):
  {{path.to.value}}                    variable substitution (dot-path into context)
  {{#if expr}}...{{else}}...{{/if}}    expr = dot-path truthiness, or  path == "lit" / path != "lit"
  {{#unless expr}}...{{/unless}}
  {{#each path}}...{{this.key}}...{{/each}}   iterate a list; item bound to `this`
Blocks may nest. Unknown variables raise TemplateError (fail loudly at init time).
Exit codes (CLI, part 2): 0 success / 1 conflicts or config validation failure / 2 usage error.
"""
import sys

if sys.version_info < (3, 9):
    sys.stderr.write("error: superrelease scripts require Python 3.9+\n")
    sys.exit(2)

import argparse
import json
import re
import stat
import subprocess
from datetime import datetime, timezone
from pathlib import Path

TAG_RE = re.compile(r"\{\{(.*?)\}\}")
COND_RE = re.compile(r'^(\S+)\s*(==|!=)\s*"([^"]*)"$')
MARKER_RE = re.compile(r"generated by superrelease v(\d+\.\d+\.\d+)")


class TemplateError(ValueError):
    pass


def tokenize(text):
    tokens, pos = [], 0
    for m in TAG_RE.finditer(text):
        if m.start() > pos:
            tokens.append(("text", text[pos:m.start()]))
        tokens.append(("tag", m.group(1).strip()))
        pos = m.end()
    if pos < len(text):
        tokens.append(("text", text[pos:]))
    return tokens


def parse(tokens):
    root = []
    stack = [("root", None, root)]
    for kind, value in tokens:
        current = stack[-1][2]
        if kind == "text":
            current.append({"kind": "text", "s": value})
        elif value.startswith("#if "):
            node = {"kind": "if", "cond": value[4:].strip(), "then": [], "else": []}
            current.append(node)
            stack.append(("if", node, node["then"]))
        elif value.startswith("#unless "):
            node = {"kind": "unless", "cond": value[8:].strip(), "body": []}
            current.append(node)
            stack.append(("unless", node, node["body"]))
        elif value.startswith("#each "):
            node = {"kind": "each", "path": value[6:].strip(), "body": []}
            current.append(node)
            stack.append(("each", node, node["body"]))
        elif value == "else":
            head, node, _ = stack[-1]
            if head != "if":
                raise TemplateError("{{else}} outside {{#if}}")
            stack[-1] = ("if", node, node["else"])
        elif value in ("/if", "/unless", "/each"):
            if len(stack) == 1:
                raise TemplateError("unexpected {{" + value + "}}")
            head, node, _ = stack.pop()
            if value != "/" + head:
                raise TemplateError("mismatched {{" + value + "}} closing {{#" + head + "}}")
        else:
            current.append({"kind": "var", "path": value})
    if len(stack) != 1:
        raise TemplateError("unclosed {{#" + stack[-1][0] + "}} block")
    return root


def lookup(ctx, dotted):
    cur = ctx
    for part in dotted.split("."):
        if isinstance(cur, dict) and part in cur:
            cur = cur[part]
        else:
            return None
    return cur


def truthy(ctx, expr):
    m = COND_RE.match(expr)
    if m:
        val = lookup(ctx, m.group(1))
        # A missing path never equals a literal (and therefore != is true).
        eq = val is not None and str(val) == m.group(3)
        return eq if m.group(2) == "==" else not eq
    return bool(lookup(ctx, expr))


def evaluate(nodes, ctx):
    out = []
    for n in nodes:
        kind = n["kind"]
        if kind == "text":
            out.append(n["s"])
        elif kind == "var":
            val = lookup(ctx, n["path"])
            if val is None:
                raise TemplateError("unknown placeholder: {{" + n["path"] + "}}")
            out.append(val if isinstance(val, str) else json.dumps(val, ensure_ascii=False))
        elif kind == "if":
            branch = n["then"] if truthy(ctx, n["cond"]) else n["else"]
            out.append(evaluate(branch, ctx))
        elif kind == "unless":
            if not truthy(ctx, n["cond"]):
                out.append(evaluate(n["body"], ctx))
        elif kind == "each":
            items = lookup(ctx, n["path"]) or []
            for item in items:
                sub = dict(ctx)
                sub["this"] = item
                out.append(evaluate(n["body"], sub))
    return "".join(out)


def render_template(text, ctx):
    return evaluate(parse(tokenize(text)), ctx)
