import json
import stat
import tempfile
import unittest
from pathlib import Path

from helpers import (ASSETS, PLUGIN_SCRIPTS, load_module, make_plugin_tree,
                     monorepo_config, run_script, scope_config, write)

RENDER = PLUGIN_SCRIPTS / "render.py"

MANIFEST = {
    "entries": [
        {"src": "skills/release/SKILL.md", "dest": ".claude/skills/release/SKILL.md",
         "render": True},
        {"src": "scripts/tool.py", "dest": ".superrelease/scripts/tool.py",
         "render": False, "executable": True},
        {"src": "templates/notes.md", "dest": ".superrelease/templates/notes.md",
         "render": True, "preserve": "template"},
        {"src": "github/release.yml", "dest": ".github/release.yml",
         "render": False, "when": "github.releaseYml"},
    ]
}
ASSET_FILES = {
    "skills/release/SKILL.md":
        "---\nname: release\ndescription: {{project.name}} 릴리스\n---\n\n"
        "# {{project.name}} release\n"
        "{{#if derived.anyTagEnabled}}TAGGED\n{{/if}}"
        "{{#unless derived.allTagEnabled}}MIXED\n{{/unless}}",
    "scripts/tool.py": "#!/usr/bin/env python3\nprint('hi')\n",
    "templates/notes.md": "# Notes {{scope.name}}\n",
    "github/release.yml": "changelog:\n  categories: []\n",
}
MARKER_MD = ("<!-- generated by superrelease v0.1.0 — do not edit; "
             "re-run init to regenerate (직접 수정하지 말고 재init 하세요) -->")


class PipelineTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        base = Path(self.tmp.name)
        self.assets = make_plugin_tree(base / "plugin", MANIFEST, ASSET_FILES)
        self.repo = base / "target-repo"
        self.repo.mkdir()
        self.config_path = self.repo / ".superrelease" / "config.json"
        self.write_config(scope_config(
            [{"file": "x.txt", "type": "regex", "pattern": "v(1)"}]))

    def write_config(self, cfg):
        write(self.config_path, json.dumps(cfg, ensure_ascii=False, indent=2))

    def render(self, *extra):
        return run_script(RENDER, "--config", self.config_path,
                          "--assets", self.assets, "--repo", self.repo, *extra)

    def test_create_renders_and_inserts_marker_after_frontmatter(self):
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        skill = (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
        lines = skill.splitlines()
        self.assertEqual(lines[0], "---")
        self.assertEqual(lines[3], "---")
        self.assertEqual(lines[4], MARKER_MD)
        self.assertIn("target-repo 릴리스", skill)  # project.name = 디렉터리명 폴백
        self.assertNotIn("{{", skill)

    def test_derived_any_tag_enabled_true(self):
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        skill = (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
        self.assertIn("TAGGED", skill)

    def test_derived_any_tag_enabled_false_when_all_tagless(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["tag"]["enabled"] = False
        cfg["scopes"][0]["notes"]["destinations"] = ["changelog"]
        cfg["github"] = {"release": False, "generateNotes": False,
                        "releaseYml": False}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        skill = (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
        self.assertNotIn("TAGGED", skill)

    def test_derived_all_tag_enabled(self):
        r = self.render()  # 단일 tagged scope → all=true → MIXED 미출력
        self.assertEqual(r.returncode, 0, r.stderr)
        skill = (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
        self.assertNotIn("MIXED", skill)

    def test_derived_all_tag_enabled_false_when_tagless(self):
        # collapse 방향(위 test_derived_all_tag_enabled)의 대칭 — expand 방향도
        # 유닛 레벨에서 커버한다(리뷰 라운드 1). 단일 scope라 "혼합"은 아니지만
        # allTagEnabled=false(tag.enabled가 전부 false)에서 {{#unless}} 본문이
        # 실제로 렌더되는지 확인한다.
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["tag"]["enabled"] = False
        cfg["scopes"][0]["notes"]["destinations"] = ["changelog"]
        cfg["github"] = {"release": False, "generateNotes": False,
                        "releaseYml": False}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        skill = (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
        self.assertIn("MIXED", skill)

    def test_verbatim_executable_and_marker_after_shebang(self):
        self.render()
        tool = self.repo / ".superrelease/scripts/tool.py"
        lines = tool.read_text(encoding="utf-8").splitlines()
        self.assertTrue(lines[0].startswith("#!"))
        self.assertTrue(lines[1].startswith("# generated by superrelease v0.1.0"))
        self.assertTrue(tool.stat().st_mode & stat.S_IXUSR)

    def test_when_false_skips(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["github"]["releaseYml"] = False
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertFalse((self.repo / ".github/release.yml").exists())
        self.assertIn("skipped", r.stdout)

    def test_unmarked_template_preserved_on_rerender(self):
        self.render()
        notes = self.repo / ".superrelease/templates/notes.md"
        write(notes, "hand edited, marker removed\n")
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(notes.read_text(encoding="utf-8"), "hand edited, marker removed\n")
        self.assertIn("preserve", r.stdout)

    def test_unmarked_non_template_conflicts_then_force(self):
        write(self.repo / ".claude/skills/release/SKILL.md", "my own skill\n")
        r = self.render("--check")
        self.assertEqual(r.returncode, 1)
        self.assertIn("conflict", r.stdout)
        self.assertEqual((self.repo / ".claude/skills/release/SKILL.md")
                         .read_text(encoding="utf-8"), "my own skill\n")
        r2 = self.render("--force")
        self.assertEqual(r2.returncode, 0, r2.stderr)
        self.assertIn("generated by superrelease",
                      (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8"))

    def test_check_reports_without_writing(self):
        r = self.render("--check")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertFalse((self.repo / ".claude").exists())
        self.assertIn("create", r.stdout)

    def test_rerender_same_config_is_unchanged(self):
        self.render()
        r = self.render("--check")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertNotIn("update", r.stdout)
        self.assertIn("unchanged", r.stdout)

    def test_unknown_placeholder_exits_1(self):
        bad = make_plugin_tree(Path(self.tmp.name) / "plugin2",
                               {"entries": [{"src": "a.md", "dest": "a.md", "render": True}]},
                               {"a.md": "{{no.such.key}}\n"})
        r = run_script(RENDER, "--config", self.config_path,
                       "--assets", bad, "--repo", self.repo)
        self.assertEqual(r.returncode, 1)
        self.assertIn("unknown placeholder", r.stderr)

    def test_invalid_config_exits_1(self):
        write(self.config_path, json.dumps({"superrelease": {}}))
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("config:", r.stderr)

    def test_maintenance_lines_rejected_for_independent(self):
        cfg = monorepo_config()
        cfg["repo"]["maintenanceLines"] = True
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("maintenanceLines", r.stderr)

    def test_release_pr_rejected_for_tagless_scope(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["releasePath"] = "release-pr"
        cfg["scopes"][0]["tag"]["enabled"] = False
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("release-pr", r.stderr)

    def test_maintenance_lines_rejected_for_non_semver_scheme(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["maintenanceLines"] = True
        cfg["scopes"][0]["scheme"] = {"type": "calver", "pattern": "YYYY.MM.MICRO"}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("semver", r.stderr)

    def test_gitflow_rejected_for_non_semver_scheme(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["branching"] = "gitflow"
        cfg["repo"]["developBranch"] = "develop"
        cfg["repo"]["releasePath"] = "release-pr"
        cfg["scopes"][0]["scheme"] = {"type": "calver", "pattern": "YYYY.MM.MICRO"}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("gitflow", r.stderr)
        self.assertIn("semver", r.stderr)

    def test_backfill_ok_for_independent(self):
        cfg = monorepo_config()  # 2 scopes, both tag.enabled=True
        cfg["repo"]["backfill"] = True
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_backfill_rejected_when_all_scopes_tagless(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["backfill"] = True
        cfg["scopes"][0]["tag"]["enabled"] = False
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("tagged scope", r.stderr)

    def test_train_rejected_as_removed(self):
        # release-train은 제거됨 — train 객체가 있으면 유효한 옛 조합이라도 거부
        cfg = monorepo_config()
        cfg["train"] = {"enabled": True,
                        "scheme": {"type": "calver", "pattern": "YYYY.MICRO"},
                        "tag": {"format": "train-{version}", "annotated": True,
                                "signed": False}}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("train", r.stderr)
        self.assertIn("no longer supported", r.stderr)

    def test_tag_message_rejected_as_removed(self):
        # tag-message 목적지는 제거됨 — annotated 태그(옛 유효 조합)여도 거부
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["tag-message"]
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("tag-message", r.stderr)
        self.assertIn("no longer supported", r.stderr)

    def test_unknown_destination_rejected(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["changelog", "release-notes"]
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("unknown notes destination", r.stderr)
        self.assertIn("release-notes", r.stderr)

    def test_fragment_rejected_without_sink(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["fragment"]
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("fragment", r.stderr)

    def test_fragment_ok_with_sink(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["fragment", "changelog"]
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_release_path_typo_rejected(self):
        # 커버리지 검토 P0 재현: "release_pr" 오타가 침묵 통과해
        # release-pr flavor 스킬 + 미렌더 release-pr-body.md 참조를 만들었다
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["releasePath"] = "release_pr"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("releasePath", r.stderr)
        self.assertIn("release_pr", r.stderr)

    def test_next_snapshot_requires_mutable_qualifier(self):
        # 커버리지 검토 P0 재현: qualifier null이면 생성 스킬의
        # `--qualifier ` 명령이 릴리스 시점 argparse 오류로 죽는다
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["preRelease"] = {"style": "none", "qualifier": None}
        cfg["scopes"][0]["postRelease"] = {"bump": "next-snapshot"}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("next-snapshot", r.stderr)
        self.assertIn("mutable", r.stderr)

    def test_tag_enabled_key_must_be_explicit(self):
        # The frozen template engine resolves a missing scope.tag.enabled
        # dot-path as falsy (truthy → lookup → _MISSING → False), while
        # validate_config's get("enabled", True) helpers assume true when the
        # key is omitted. That divergence let a hand-edited config with the
        # "enabled" key deleted pass validation (exit 0) yet render a
        # contradictory toolkit — gh release create present, tag-creation
        # body and stall-detection absent (M4a final review #1). Require the
        # key to be an explicit boolean so the engine/validate gap can't be
        # exploited.
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["tag"] = {"format": "v{version}", "annotated": True}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("tag.enabled must be an explicit boolean", r.stderr)

    def test_missing_manifest_exits_2(self):
        assets = make_plugin_tree(Path(self.tmp.name) / "plugin-no-manifest",
                                  MANIFEST, ASSET_FILES)
        (assets / "manifest.json").unlink()
        r = run_script(RENDER, "--config", self.config_path,
                       "--assets", assets, "--repo", self.repo)
        self.assertEqual(r.returncode, 2)
        self.assertIn("manifest not found", r.stderr)

    def test_branching_enum_rejected(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["branching"] = "git-flow"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("repo.branching", r.stderr)

    def test_gitflow_requires_release_pr(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["branching"] = "gitflow"
        cfg["repo"]["developBranch"] = "develop"  # releasePath는 기본 direct-push
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("release-pr", r.stderr)

    def test_gitflow_monorepo_allowed(self):
        cfg = monorepo_config()
        cfg["repo"]["branching"] = "gitflow"
        cfg["repo"]["developBranch"] = "develop"
        cfg["repo"]["releasePath"] = "release-pr"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_gitflow_tagless_release_pr_allowed(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["branching"] = "gitflow"
        cfg["repo"]["developBranch"] = "develop"
        cfg["repo"]["releasePath"] = "release-pr"
        cfg["scopes"][0]["tag"]["enabled"] = False
        cfg["scopes"][0]["notes"]["destinations"] = ["changelog"]
        cfg["github"] = {"release": False, "generateNotes": False,
                        "releaseYml": False}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_bundle_requires_independent(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["bundle"] = {"enabled": True,
                         "scheme": {"type": "calver", "pattern": "YYYY.0M.MICRO"},
                         "notesPath": "docs/releases/"}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("independent", r.stderr)

    def test_bundle_requires_calver_and_pattern(self):
        cfg = monorepo_config()
        cfg["bundle"] = {"enabled": True,
                         "scheme": {"type": "semver", "pattern": ""},
                         "notesPath": "docs/releases/"}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("calver", r.stderr)
        self.assertIn("bundle.scheme.pattern", r.stderr)

    def test_bundle_requires_notes_path(self):
        cfg = monorepo_config()
        cfg["bundle"] = {"enabled": True,
                         "scheme": {"type": "calver", "pattern": "YYYY.0M.MICRO"}}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("bundle.notesPath", r.stderr)

    def test_bundle_ok_for_trunk_monorepo(self):
        # bundle은 branching 무관 — trunk 모노레포 라운드에도 허용 (회귀 핀)
        cfg = monorepo_config()
        cfg["bundle"] = {"enabled": True,
                         "scheme": {"type": "calver", "pattern": "YYYY.0M.MICRO"},
                         "notesPath": "docs/releases/"}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_gitflow_requires_develop_branch(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["branching"] = "gitflow"
        cfg["repo"]["releasePath"] = "release-pr"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("developBranch", r.stderr)

    def test_gitflow_develop_must_differ_from_default(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["branching"] = "gitflow"
        cfg["repo"]["releasePath"] = "release-pr"
        cfg["repo"]["developBranch"] = "main"  # defaultBranch와 동일
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("must differ", r.stderr)

    def test_crlf_dest_preserved_on_update(self):
        self.render()
        notes = self.repo / ".superrelease/templates/notes.md"
        write(notes, notes.read_text(encoding="utf-8").replace("\n", "\r\n"))
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["name"] = "core"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        raw = notes.read_bytes()
        self.assertIn(b"\r\n", raw)
        self.assertIn(b"Notes core", raw)

    def test_unknown_scheme_type_exits_1(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["scheme"] = {"type": "sequential", "pattern": None}
        cfg["scopes"][0]["preRelease"] = {"style": "none", "qualifier": None}
        cfg["scopes"][0]["postRelease"] = {"bump": "none"}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("scheme.type", r.stderr)
        self.assertIn("sequential", r.stderr)

    def test_calver_with_mutable_prerelease_and_next_snapshot_exits_1(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["scheme"] = {"type": "calver", "pattern": "YYYY.MM.MICRO"}
        # scope_config 기본값이 preRelease mutable + postRelease next-snapshot
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("preRelease.style", r.stderr)
        self.assertIn("postRelease.bump", r.stderr)

    def test_headver_with_next_snapshot_exits_1(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["scheme"] = {"type": "headver", "pattern": "1"}
        cfg["scopes"][0]["preRelease"] = {"style": "none", "qualifier": None}
        self.write_config(cfg)  # postRelease는 기본 next-snapshot 유지
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("postRelease.bump", r.stderr)

    def test_location_missing_required_key_exits_1(self):
        cfg = scope_config([{"file": "package.json", "type": "json-path"}])
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("versionLocations[0].path", r.stderr)

    def test_location_unknown_type_exits_1(self):
        cfg = scope_config([{"file": "x.yaml", "type": "yaml-path", "path": "v"}])
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("versionLocations[0].type", r.stderr)

    def test_location_regex_two_groups_exits_1(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "(a)-(b)"}])
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("exactly one capture group", r.stderr)

    def test_location_regex_invalid_exits_1(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1"}])
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("not a valid regex", r.stderr)

    def test_scan_version_patterns_pass_validation(self):
        # scan이 버전 위치로 제안하는 regex는 전부 validate를 통과해야 한다 —
        # 하나라도 걸리면 init이 만든 config가 렌더 시점에 거부된다.
        # 새 패턴 상수가 늘면 이 테스트가 자동으로 함께 검사한다.
        scan = load_module(PLUGIN_SCRIPTS / "scan.py", "scan_for_patterns")
        render_mod = load_module(PLUGIN_SCRIPTS / "render.py", "render_for_patterns")
        patterns = {n: v for n, v in vars(scan).items()
                    if n.endswith("_PATTERN") and isinstance(v, str)}
        self.assertGreaterEqual(len(patterns), 9, "패턴 상수 수집 실패")
        for name, pattern in sorted(patterns.items()):
            with self.subTest(pattern=name):
                cfg = scope_config([{"file": "x", "type": "regex",
                                     "pattern": pattern}])
                self.assertEqual(render_mod.validate_config(cfg), [])

    def test_github_release_with_tagless_scope_exits_1(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["tag"]["enabled"] = False
        cfg["scopes"][0]["notes"]["destinations"] = ["changelog"]
        self.write_config(cfg)  # github.release 기본 true
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("github.release", r.stderr)

    def test_github_release_dest_without_github_release_exits_1(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["github"]["release"] = False
        self.write_config(cfg)  # destinations 기본에 github-release 포함
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("github-release", r.stderr)

    def test_required_fields_reported_individually(self):
        # 기존 통짜 빈 config 테스트를 보완 — 규칙별 단독 케이스
        cases = [
            (lambda c: c["scopes"][0].pop("name"), "scopes[0].name"),
            (lambda c: c["scopes"][0].pop("path"), "scopes[0].path"),
            (lambda c: c["scopes"][0].update(scheme={}), "scheme.type is required"),
            (lambda c: c["scopes"][0].update(versionLocations=[]),
             "versionLocations is required"),
            (lambda c: c["repo"].pop("releasePath"), "repo.releasePath"),
            (lambda c: c["superrelease"].pop("configVersion"), "configVersion"),
        ]
        for mutate, expect in cases:
            with self.subTest(expect=expect):
                cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
                mutate(cfg)
                self.write_config(cfg)
                r = self.render()
                self.assertEqual(r.returncode, 1)
                self.assertIn(expect, r.stderr)

    def test_gitflow_maintenance_lines_rejected(self):
        # manifest의 hotfix 이중 entry가 같은 목적지에 렌더 — gitflow flavor만
        # 남고 유지보수 라인 기대가 소리 없이 증발하는 조합
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["branching"] = "gitflow"
        cfg["repo"]["developBranch"] = "develop"
        cfg["repo"]["releasePath"] = "release-pr"
        cfg["repo"]["maintenanceLines"] = True
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("maintenanceLines", r.stderr)
        self.assertIn("gitflow", r.stderr)

    def test_moving_major_tag_requires_semver(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["scheme"] = {"type": "calver", "pattern": "YYYY.MM.MICRO"}
        cfg["scopes"][0]["preRelease"] = {"style": "none", "qualifier": None}
        cfg["scopes"][0]["postRelease"] = {"bump": "none"}
        cfg["scopes"][0]["tag"]["movingMajorTag"] = True
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("movingMajorTag", r.stderr)
        self.assertIn("semver", r.stderr)

    def test_moving_major_tag_rejected_for_independent(self):
        # release-monorepo의 `git tag -f v<major>`는 scope 네임스페이스가 없어
        # 같은 major의 scope끼리 충돌한다
        cfg = monorepo_config()
        cfg["scopes"][0]["tag"]["movingMajorTag"] = True
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("movingMajorTag", r.stderr)
        self.assertIn("independent", r.stderr)

    def test_calver_headver_require_pattern(self):
        for scheme in ("calver", "headver"):
            with self.subTest(scheme=scheme):
                cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
                cfg["scopes"][0]["scheme"] = {"type": scheme, "pattern": None}
                cfg["scopes"][0]["preRelease"] = {"style": "none", "qualifier": None}
                cfg["scopes"][0]["postRelease"] = {"bump": "none"}
                self.write_config(cfg)
                r = self.render()
                self.assertEqual(r.returncode, 1)
                self.assertIn("scheme.pattern", r.stderr)

    def test_multiple_scopes_require_independent(self):
        # 헬퍼가 strategy에 맞는 releaseCommitFormat을 주므로 위반은 scope 수
        # 하나뿐이다 — 다른 규칙에 걸려 통과하는 위양성이 없다.
        cfg = monorepo_config(strategy="fixed")  # 2 scopes + fixed
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("multiple scopes", r.stderr)

    def test_duplicate_scope_names_rejected(self):
        cfg = monorepo_config()
        cfg["scopes"][1]["name"] = cfg["scopes"][0]["name"]
        cfg["scopes"][1]["tag"]["format"] = "dup2@{version}"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        # 어느 scope가 충돌인지 지목해야 한다 — scope가 3개 이상이면
        # "unique"만으로는 고칠 대상을 찾을 수 없다.
        self.assertIn("scopes[1]: scope names must be unique", r.stderr)
        self.assertIn("already used by scopes[0]", r.stderr)

    def test_duplicate_tag_formats_rejected(self):
        cfg = monorepo_config()
        cfg["scopes"][1]["tag"]["format"] = cfg["scopes"][0]["tag"]["format"]
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("scopes[1]: tag.format must be unique", r.stderr)
        self.assertIn("already used by scopes[0]", r.stderr)

    def test_release_file_requires_per_release_path(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["release-file"]
        cfg["scopes"][0]["notes"]["perReleasePath"] = None
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("perReleasePath", r.stderr)

    def test_release_commit_format_placeholders(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["releaseCommitFormat"] = "chore(release): {scope}@{version}"
        self.write_config(cfg)  # 단일 레포에 {scope}
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("{scope}", r.stderr, "single repo with {scope}")
        cfg["repo"]["releaseCommitFormat"] = "release commit"  # {version} 없음
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("{version}", r.stderr, "missing {version}")

    def test_closed_sets_language_destinations_merge_policy(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["language"] = "jp"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("notes.language", r.stderr, "invalid language jp")
        cfg["scopes"][0]["notes"]["language"] = "ko"
        cfg["scopes"][0]["notes"]["destinations"] = []
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("destinations", r.stderr, "empty destinations")
        cfg["scopes"][0]["notes"]["destinations"] = ["changelog"]
        cfg["repo"]["mergePolicy"] = "ff-only"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("mergePolicy", r.stderr, "invalid mergePolicy ff-only")

    def test_missing_required_fields_say_required_not_got_none(self):
        # 부재·null은 오타가 아니라 누락이다 — 'got "None"'으로 보고하면
        # 사용자가 자기가 뭘 잘못 적었는지 찾느라 헤맨다.
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        del cfg["repo"]["mergePolicy"]
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("repo.mergePolicy is required", r.stderr)
        self.assertNotIn('got "None"', r.stderr)
        cfg["repo"]["mergePolicy"] = "squash"
        cfg["scopes"][0]["notes"]["language"] = None
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("notes.language is required", r.stderr)
        self.assertNotIn('got "None"', r.stderr)

    def test_calver_next_snapshot_gives_one_exit(self):
        # calver 규칙("bump는 none")과 next-snapshot 규칙("preRelease를
        # mutable로")이 함께 발화하면 서로를 무효화하는 수정 루프가 된다.
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["scheme"] = {"type": "calver", "pattern": "YYYY.MM.MICRO"}
        cfg["scopes"][0]["preRelease"] = {"style": "none", "qualifier": None}
        cfg["scopes"][0]["postRelease"] = {"bump": "next-snapshot"}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn('postRelease.bump must be "none" for calver/headver',
                      r.stderr)
        self.assertNotIn('requires preRelease.style "mutable"', r.stderr)


SWITCH_MANIFEST = {
    "entries": [
        {"src": "skills/single.md", "dest": ".claude/skills/release/SKILL.md",
         "render": True, "when": 'repo.monorepoStrategy != "independent"'},
        {"src": "skills/mono.md", "dest": ".claude/skills/release/SKILL.md",
         "render": True, "when": 'repo.monorepoStrategy == "independent"'},
    ]
}
SWITCH_FILES = {
    "skills/single.md": "SINGLE {{project.name}}\n",
    "skills/mono.md": "MONO {{project.name}}\n",
}


class SameDestSwitchTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        base = Path(self.tmp.name)
        self.assets = make_plugin_tree(base / "plugin", SWITCH_MANIFEST, SWITCH_FILES)
        self.repo = base / "target-repo"
        self.repo.mkdir()
        self.config_path = self.repo / ".superrelease" / "config.json"

    def render_with(self, cfg):
        write(self.config_path, json.dumps(cfg, ensure_ascii=False, indent=2))
        return run_script(PLUGIN_SCRIPTS / "render.py", "--config", self.config_path,
                          "--assets", self.assets, "--repo", self.repo)

    def dest_text(self):
        return (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")

    def test_single_variant_for_non_monorepo(self):
        r = self.render_with(scope_config(
            [{"file": "x", "type": "regex", "pattern": "v(1)"}]))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("SINGLE", self.dest_text())
        self.assertIn("skipped", r.stdout)

    def test_mono_variant_for_independent(self):
        r = self.render_with(monorepo_config())
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("MONO", self.dest_text())
        self.assertNotIn("SINGLE", self.dest_text())


class MonorepoValidateTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        base = Path(self.tmp.name)
        self.assets = make_plugin_tree(base / "plugin", SWITCH_MANIFEST, SWITCH_FILES)
        self.repo = base / "target-repo"
        self.repo.mkdir()
        self.config_path = self.repo / ".superrelease" / "config.json"

    def render_with(self, cfg):
        write(self.config_path, json.dumps(cfg, ensure_ascii=False, indent=2))
        return run_script(PLUGIN_SCRIPTS / "render.py", "--config", self.config_path,
                          "--assets", self.assets, "--repo", self.repo)

    def test_monorepo_without_strategy_exits_1(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["kind"] = "monorepo"  # monorepoStrategy는 None 그대로
        r = self.render_with(cfg)
        self.assertEqual(r.returncode, 1)
        self.assertIn("monorepoStrategy", r.stderr)

    def test_independent_with_single_scope_exits_1(self):
        cfg = monorepo_config()
        cfg["scopes"] = cfg["scopes"][:1]
        r = self.render_with(cfg)
        self.assertEqual(r.returncode, 1)
        self.assertIn("at least two scopes", r.stderr)

    def test_strategy_without_monorepo_kind_exits_1(self):
        cfg = monorepo_config()
        cfg["repo"]["kind"] = "app"   # strategy는 "independent"인데 kind는 app
        r = self.render_with(cfg)
        self.assertEqual(r.returncode, 1)
        self.assertIn("monorepoStrategy is only valid", r.stderr)


class ChangedPackagesGateTest(unittest.TestCase):
    def _render(self, cfg, files):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        repo = Path(tmp.name)
        write(repo / ".superrelease" / "config.json",
              json.dumps(cfg, ensure_ascii=False, indent=2))
        for rel, content in files.items():
            write(repo / rel, content)
        r = run_script(PLUGIN_SCRIPTS / "render.py",
                       "--config", repo / ".superrelease" / "config.json",
                       "--assets", ASSETS, "--repo", repo)
        self.assertEqual(r.returncode, 0, r.stderr)
        return repo

    def test_independent_deploys_changed_packages(self):
        repo = self._render(monorepo_config(), {
            "packages/a/package.json": '{\n  "name": "a",\n  "version": "0.1.0"\n}\n',
            "packages/b/package.json": '{\n  "name": "b",\n  "version": "0.1.0"\n}\n'})
        self.assertTrue((repo / ".superrelease/scripts/changed-packages.py").is_file())

    def test_fixed_monorepo_does_not_deploy_changed_packages(self):
        cfg = monorepo_config(strategy="fixed")
        cfg["scopes"] = cfg["scopes"][:1]      # fixed = 단일 scope 모델
        cfg["scopes"][0]["name"] = "root"
        cfg["scopes"][0]["path"] = "."
        cfg["scopes"][0]["versionLocations"] = [
            {"file": "gradle.properties", "type": "properties-key", "key": "version"}]
        # monorepo_config()의 releaseCommitFormat은 independent 전용 {scope}
        # placeholder를 쓴다 — fixed는 단일 scope 모델이라 B-17 닫힌 집합 규칙이
        # 거부한다(2026-08-06 Task 3에서 발견); 단일 scope에 맞는 포맷으로 오버라이드.
        cfg["repo"]["releaseCommitFormat"] = "chore(release): {version}"
        repo = self._render(cfg, {"gradle.properties": "version=0.1.0\n"})
        self.assertFalse((repo / ".superrelease/scripts/changed-packages.py").exists())
        # fixed는 단일 변형 스킬을 받는다 (모노레포 변형이 아님)
        skill_text = (repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
        self.assertIn("릴리스 오케스트레이터", skill_text)
        self.assertNotIn("모노레포", skill_text)


if __name__ == "__main__":
    unittest.main()
