import json
import stat
import tempfile
import unittest
from pathlib import Path

from helpers import (ASSETS, PLUGIN_SCRIPTS, make_plugin_tree, monorepo_config, run_script,
                     scope_config, write)

RENDER = PLUGIN_SCRIPTS / "render.py"

MANIFEST = {
    "entries": [
        {"src": "skills/release/SKILL.md", "dest": ".claude/skills/release/SKILL.md",
         "render": True},
        {"src": "scripts/tool.py", "dest": ".superrelease/scripts/tool.py",
         "render": False, "executable": True},
        {"src": "templates/notes.md", "dest": ".superrelease/templates/notes.md",
         "render": True, "preserve": "template"},
        {"src": "github/release.yml", "dest": ".github/release.yml",
         "render": False, "when": "github.releaseYml"},
    ]
}
ASSET_FILES = {
    "skills/release/SKILL.md":
        "---\nname: release\ndescription: {{project.name}} 릴리스\n---\n\n# {{project.name}} release\n",
    "scripts/tool.py": "#!/usr/bin/env python3\nprint('hi')\n",
    "templates/notes.md": "# Notes {{scope.name}}\n",
    "github/release.yml": "changelog:\n  categories: []\n",
}
MARKER_MD = ("<!-- generated by superrelease v0.1.0 — do not edit; "
             "re-run init to regenerate (직접 수정하지 말고 재init 하세요) -->")


class PipelineTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        base = Path(self.tmp.name)
        self.assets = make_plugin_tree(base / "plugin", MANIFEST, ASSET_FILES)
        self.repo = base / "target-repo"
        self.repo.mkdir()
        self.config_path = self.repo / ".superrelease" / "config.json"
        self.write_config(scope_config(
            [{"file": "x.txt", "type": "regex", "pattern": "v(1)"}]))

    def write_config(self, cfg):
        write(self.config_path, json.dumps(cfg, ensure_ascii=False, indent=2))

    def render(self, *extra):
        return run_script(RENDER, "--config", self.config_path,
                          "--assets", self.assets, "--repo", self.repo, *extra)

    def test_create_renders_and_inserts_marker_after_frontmatter(self):
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        skill = (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
        lines = skill.splitlines()
        self.assertEqual(lines[0], "---")
        self.assertEqual(lines[3], "---")
        self.assertEqual(lines[4], MARKER_MD)
        self.assertIn("target-repo 릴리스", skill)  # project.name = 디렉터리명 폴백
        self.assertNotIn("{{", skill)

    def test_verbatim_executable_and_marker_after_shebang(self):
        self.render()
        tool = self.repo / ".superrelease/scripts/tool.py"
        lines = tool.read_text(encoding="utf-8").splitlines()
        self.assertTrue(lines[0].startswith("#!"))
        self.assertTrue(lines[1].startswith("# generated by superrelease v0.1.0"))
        self.assertTrue(tool.stat().st_mode & stat.S_IXUSR)

    def test_when_false_skips(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["github"]["releaseYml"] = False
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertFalse((self.repo / ".github/release.yml").exists())
        self.assertIn("skipped", r.stdout)

    def test_unmarked_template_preserved_on_rerender(self):
        self.render()
        notes = self.repo / ".superrelease/templates/notes.md"
        write(notes, "hand edited, marker removed\n")
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(notes.read_text(encoding="utf-8"), "hand edited, marker removed\n")
        self.assertIn("preserve", r.stdout)

    def test_unmarked_non_template_conflicts_then_force(self):
        write(self.repo / ".claude/skills/release/SKILL.md", "my own skill\n")
        r = self.render("--check")
        self.assertEqual(r.returncode, 1)
        self.assertIn("conflict", r.stdout)
        self.assertEqual((self.repo / ".claude/skills/release/SKILL.md")
                         .read_text(encoding="utf-8"), "my own skill\n")
        r2 = self.render("--force")
        self.assertEqual(r2.returncode, 0, r2.stderr)
        self.assertIn("generated by superrelease",
                      (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8"))

    def test_check_reports_without_writing(self):
        r = self.render("--check")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertFalse((self.repo / ".claude").exists())
        self.assertIn("create", r.stdout)

    def test_rerender_same_config_is_unchanged(self):
        self.render()
        r = self.render("--check")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertNotIn("update", r.stdout)
        self.assertIn("unchanged", r.stdout)

    def test_unknown_placeholder_exits_1(self):
        bad = make_plugin_tree(Path(self.tmp.name) / "plugin2",
                               {"entries": [{"src": "a.md", "dest": "a.md", "render": True}]},
                               {"a.md": "{{no.such.key}}\n"})
        r = run_script(RENDER, "--config", self.config_path,
                       "--assets", bad, "--repo", self.repo)
        self.assertEqual(r.returncode, 1)
        self.assertIn("unknown placeholder", r.stderr)

    def test_invalid_config_exits_1(self):
        write(self.config_path, json.dumps({"superrelease": {}}))
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("config:", r.stderr)

    def test_maintenance_lines_rejected_for_independent(self):
        cfg = monorepo_config()
        cfg["repo"]["maintenanceLines"] = True
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("maintenanceLines", r.stderr)

    def test_release_pr_rejected_for_tagless_scope(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["releasePath"] = "release-pr"
        cfg["scopes"][0]["tag"]["enabled"] = False
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("release-pr", r.stderr)

    def test_maintenance_lines_rejected_for_non_semver_scheme(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["maintenanceLines"] = True
        cfg["scopes"][0]["scheme"] = {"type": "calver", "pattern": "YYYY.MM.MICRO"}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("semver", r.stderr)

    def test_backfill_rejected_for_independent(self):
        cfg = monorepo_config()
        cfg["repo"]["backfill"] = True
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("backfill", r.stderr)

    def test_tag_message_rejected_without_annotated_or_signed(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["tag-message"]
        cfg["scopes"][0]["tag"] = {"enabled": True, "format": "v{version}",
                                   "annotated": False, "signed": False,
                                   "movingMajorTag": False}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("tag-message", r.stderr)

    def test_tag_message_ok_with_annotated(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["tag-message"]
        # default scope_config tag is annotated=True → valid
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_fragment_rejected_without_sink(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["fragment"]
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("fragment", r.stderr)

    def test_fragment_ok_with_sink(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["fragment", "changelog"]
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_tag_message_ok_when_enabled_key_omitted(self):
        # tag object present, annotated true, but "enabled" key omitted →
        # treated as enabled (sibling-rule convention), so tag-message is valid.
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["tag-message"]
        cfg["scopes"][0]["tag"] = {"format": "v{version}", "annotated": True}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)

    def test_tag_message_rejected_when_tag_disabled(self):
        # explicit enabled=false → no tag → tag-message cannot apply → reject.
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["notes"]["destinations"] = ["tag-message"]
        cfg["scopes"][0]["tag"] = {"enabled": False, "format": "v{version}",
                                   "annotated": True}
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("tag-message", r.stderr)

    def test_missing_manifest_exits_2(self):
        assets = make_plugin_tree(Path(self.tmp.name) / "plugin-no-manifest",
                                  MANIFEST, ASSET_FILES)
        (assets / "manifest.json").unlink()
        r = run_script(RENDER, "--config", self.config_path,
                       "--assets", assets, "--repo", self.repo)
        self.assertEqual(r.returncode, 2)
        self.assertIn("manifest not found", r.stderr)

    def test_crlf_dest_preserved_on_update(self):
        self.render()
        notes = self.repo / ".superrelease/templates/notes.md"
        write(notes, notes.read_text(encoding="utf-8").replace("\n", "\r\n"))
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["name"] = "core"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        raw = notes.read_bytes()
        self.assertIn(b"\r\n", raw)
        self.assertIn(b"Notes core", raw)


SWITCH_MANIFEST = {
    "entries": [
        {"src": "skills/single.md", "dest": ".claude/skills/release/SKILL.md",
         "render": True, "when": 'repo.monorepoStrategy != "independent"'},
        {"src": "skills/mono.md", "dest": ".claude/skills/release/SKILL.md",
         "render": True, "when": 'repo.monorepoStrategy == "independent"'},
    ]
}
SWITCH_FILES = {
    "skills/single.md": "SINGLE {{project.name}}\n",
    "skills/mono.md": "MONO {{project.name}}\n",
}


class SameDestSwitchTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        base = Path(self.tmp.name)
        self.assets = make_plugin_tree(base / "plugin", SWITCH_MANIFEST, SWITCH_FILES)
        self.repo = base / "target-repo"
        self.repo.mkdir()
        self.config_path = self.repo / ".superrelease" / "config.json"

    def render_with(self, cfg):
        write(self.config_path, json.dumps(cfg, ensure_ascii=False, indent=2))
        return run_script(PLUGIN_SCRIPTS / "render.py", "--config", self.config_path,
                          "--assets", self.assets, "--repo", self.repo)

    def dest_text(self):
        return (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")

    def test_single_variant_for_non_monorepo(self):
        r = self.render_with(scope_config(
            [{"file": "x", "type": "regex", "pattern": "v(1)"}]))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("SINGLE", self.dest_text())
        self.assertIn("skipped", r.stdout)

    def test_mono_variant_for_independent(self):
        r = self.render_with(monorepo_config())
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("MONO", self.dest_text())
        self.assertNotIn("SINGLE", self.dest_text())


class MonorepoValidateTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        base = Path(self.tmp.name)
        self.assets = make_plugin_tree(base / "plugin", SWITCH_MANIFEST, SWITCH_FILES)
        self.repo = base / "target-repo"
        self.repo.mkdir()
        self.config_path = self.repo / ".superrelease" / "config.json"

    def render_with(self, cfg):
        write(self.config_path, json.dumps(cfg, ensure_ascii=False, indent=2))
        return run_script(PLUGIN_SCRIPTS / "render.py", "--config", self.config_path,
                          "--assets", self.assets, "--repo", self.repo)

    def test_monorepo_without_strategy_exits_1(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["repo"]["kind"] = "monorepo"  # monorepoStrategy는 None 그대로
        r = self.render_with(cfg)
        self.assertEqual(r.returncode, 1)
        self.assertIn("monorepoStrategy", r.stderr)

    def test_independent_with_single_scope_exits_1(self):
        cfg = monorepo_config()
        cfg["scopes"] = cfg["scopes"][:1]
        r = self.render_with(cfg)
        self.assertEqual(r.returncode, 1)
        self.assertIn("at least two scopes", r.stderr)

    def test_strategy_without_monorepo_kind_exits_1(self):
        cfg = monorepo_config()
        cfg["repo"]["kind"] = "app"   # strategy는 "independent"인데 kind는 app
        r = self.render_with(cfg)
        self.assertEqual(r.returncode, 1)
        self.assertIn("monorepoStrategy is only valid", r.stderr)


class ChangedPackagesGateTest(unittest.TestCase):
    def _render(self, cfg, files):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        repo = Path(tmp.name)
        write(repo / ".superrelease" / "config.json",
              json.dumps(cfg, ensure_ascii=False, indent=2))
        for rel, content in files.items():
            write(repo / rel, content)
        r = run_script(PLUGIN_SCRIPTS / "render.py",
                       "--config", repo / ".superrelease" / "config.json",
                       "--assets", ASSETS, "--repo", repo)
        self.assertEqual(r.returncode, 0, r.stderr)
        return repo

    def test_independent_deploys_changed_packages(self):
        repo = self._render(monorepo_config(), {
            "packages/a/package.json": '{\n  "name": "a",\n  "version": "0.1.0"\n}\n',
            "packages/b/package.json": '{\n  "name": "b",\n  "version": "0.1.0"\n}\n'})
        self.assertTrue((repo / ".superrelease/scripts/changed-packages.py").is_file())

    def test_fixed_monorepo_does_not_deploy_changed_packages(self):
        cfg = monorepo_config(strategy="fixed")
        cfg["scopes"] = cfg["scopes"][:1]      # fixed = 단일 scope 모델
        cfg["scopes"][0]["name"] = "root"
        cfg["scopes"][0]["path"] = "."
        cfg["scopes"][0]["versionLocations"] = [
            {"file": "gradle.properties", "type": "properties-key", "key": "version"}]
        repo = self._render(cfg, {"gradle.properties": "version=0.1.0\n"})
        self.assertFalse((repo / ".superrelease/scripts/changed-packages.py").exists())
        # fixed는 단일 변형 스킬을 받는다 (모노레포 변형이 아님)
        skill_text = (repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
        self.assertIn("릴리스 오케스트레이터", skill_text)
        self.assertNotIn("모노레포", skill_text)


if __name__ == "__main__":
    unittest.main()
