import json
import stat
import tempfile
import unittest
from pathlib import Path

from helpers import PLUGIN_SCRIPTS, make_plugin_tree, run_script, scope_config, write

RENDER = PLUGIN_SCRIPTS / "render.py"

MANIFEST = {
    "entries": [
        {"src": "skills/release/SKILL.md", "dest": ".claude/skills/release/SKILL.md",
         "render": True},
        {"src": "scripts/tool.py", "dest": ".superrelease/scripts/tool.py",
         "render": False, "executable": True},
        {"src": "templates/notes.md", "dest": ".superrelease/templates/notes.md",
         "render": True, "preserve": "template"},
        {"src": "github/release.yml", "dest": ".github/release.yml",
         "render": False, "when": "github.releaseYml"},
    ]
}
ASSET_FILES = {
    "skills/release/SKILL.md":
        "---\nname: release\ndescription: {{project.name}} 릴리스\n---\n\n# {{project.name}} release\n",
    "scripts/tool.py": "#!/usr/bin/env python3\nprint('hi')\n",
    "templates/notes.md": "# Notes {{scope.name}}\n",
    "github/release.yml": "changelog:\n  categories: []\n",
}
MARKER_MD = ("<!-- generated by superrelease v0.1.0 — do not edit; "
             "re-run init to regenerate (직접 수정하지 말고 재init 하세요) -->")


class PipelineTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        base = Path(self.tmp.name)
        self.assets = make_plugin_tree(base / "plugin", MANIFEST, ASSET_FILES)
        self.repo = base / "target-repo"
        self.repo.mkdir()
        self.config_path = self.repo / ".superrelease" / "config.json"
        self.write_config(scope_config(
            [{"file": "x.txt", "type": "regex", "pattern": "v(1)"}]))

    def write_config(self, cfg):
        write(self.config_path, json.dumps(cfg, ensure_ascii=False, indent=2))

    def render(self, *extra):
        return run_script(RENDER, "--config", self.config_path,
                          "--assets", self.assets, "--repo", self.repo, *extra)

    def test_create_renders_and_inserts_marker_after_frontmatter(self):
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        skill = (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
        lines = skill.splitlines()
        self.assertEqual(lines[0], "---")
        self.assertEqual(lines[3], "---")
        self.assertEqual(lines[4], MARKER_MD)
        self.assertIn("target-repo 릴리스", skill)  # project.name = 디렉터리명 폴백
        self.assertNotIn("{{", skill)

    def test_verbatim_executable_and_marker_after_shebang(self):
        self.render()
        tool = self.repo / ".superrelease/scripts/tool.py"
        lines = tool.read_text(encoding="utf-8").splitlines()
        self.assertTrue(lines[0].startswith("#!"))
        self.assertTrue(lines[1].startswith("# generated by superrelease v0.1.0"))
        self.assertTrue(tool.stat().st_mode & stat.S_IXUSR)

    def test_when_false_skips(self):
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["github"]["releaseYml"] = False
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertFalse((self.repo / ".github/release.yml").exists())
        self.assertIn("skipped", r.stdout)

    def test_unmarked_template_preserved_on_rerender(self):
        self.render()
        notes = self.repo / ".superrelease/templates/notes.md"
        write(notes, "hand edited, marker removed\n")
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(notes.read_text(encoding="utf-8"), "hand edited, marker removed\n")
        self.assertIn("preserve", r.stdout)

    def test_unmarked_non_template_conflicts_then_force(self):
        write(self.repo / ".claude/skills/release/SKILL.md", "my own skill\n")
        r = self.render("--check")
        self.assertEqual(r.returncode, 1)
        self.assertIn("conflict", r.stdout)
        self.assertEqual((self.repo / ".claude/skills/release/SKILL.md")
                         .read_text(encoding="utf-8"), "my own skill\n")
        r2 = self.render("--force")
        self.assertEqual(r2.returncode, 0, r2.stderr)
        self.assertIn("generated by superrelease",
                      (self.repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8"))

    def test_check_reports_without_writing(self):
        r = self.render("--check")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertFalse((self.repo / ".claude").exists())
        self.assertIn("create", r.stdout)

    def test_rerender_same_config_is_unchanged(self):
        self.render()
        r = self.render("--check")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertNotIn("update", r.stdout)
        self.assertIn("unchanged", r.stdout)

    def test_unknown_placeholder_exits_1(self):
        bad = make_plugin_tree(Path(self.tmp.name) / "plugin2",
                               {"entries": [{"src": "a.md", "dest": "a.md", "render": True}]},
                               {"a.md": "{{no.such.key}}\n"})
        r = run_script(RENDER, "--config", self.config_path,
                       "--assets", bad, "--repo", self.repo)
        self.assertEqual(r.returncode, 1)
        self.assertIn("unknown placeholder", r.stderr)

    def test_invalid_config_exits_1(self):
        write(self.config_path, json.dumps({"superrelease": {}}))
        r = self.render()
        self.assertEqual(r.returncode, 1)
        self.assertIn("config:", r.stderr)

    def test_missing_manifest_exits_2(self):
        assets = make_plugin_tree(Path(self.tmp.name) / "plugin-no-manifest",
                                  MANIFEST, ASSET_FILES)
        (assets / "manifest.json").unlink()
        r = run_script(RENDER, "--config", self.config_path,
                       "--assets", assets, "--repo", self.repo)
        self.assertEqual(r.returncode, 2)
        self.assertIn("manifest not found", r.stderr)

    def test_crlf_dest_preserved_on_update(self):
        self.render()
        notes = self.repo / ".superrelease/templates/notes.md"
        write(notes, notes.read_text(encoding="utf-8").replace("\n", "\r\n"))
        cfg = scope_config([{"file": "x", "type": "regex", "pattern": "v(1)"}])
        cfg["scopes"][0]["name"] = "core"
        self.write_config(cfg)
        r = self.render()
        self.assertEqual(r.returncode, 0, r.stderr)
        raw = notes.read_bytes()
        self.assertIn(b"\r\n", raw)
        self.assertIn(b"Notes core", raw)


if __name__ == "__main__":
    unittest.main()
