import json
import tempfile
import unittest
from pathlib import Path

from helpers import (ASSETS, PLUGIN_SCRIPTS, load_module, monorepo_config,
                     run_script, scope_config, write)

render = load_module(PLUGIN_SCRIPTS / "render.py", "render_for_assets")


def base_ctx(**overrides):
    cfg = scope_config(
        [{"file": "gradle.properties", "type": "properties-key", "key": "version"}])
    cfg.update(overrides)
    ctx = dict(cfg)
    ctx["project"] = {"name": "demo-app"}
    ctx["plugin"] = {"version": "0.1.0"}
    ctx["generated"] = {"at": "2026-01-01T00:00:00+00:00"}
    ctx["scope"] = cfg["scopes"][0]
    return ctx


def mono_ctx(**overrides):
    cfg = monorepo_config()
    cfg.update(overrides)
    ctx = dict(cfg)
    ctx["project"] = {"name": "demo-mono"}
    ctx["plugin"] = {"version": "0.1.0"}
    ctx["generated"] = {"at": "2026-01-01T00:00:00+00:00"}
    ctx["scope"] = cfg["scopes"][0]
    return ctx


class SkillAssetsTest(unittest.TestCase):
    def render_asset(self, rel, ctx=None):
        text = (ASSETS / rel).read_text(encoding="utf-8")
        return render.render_template(text, ctx or base_ctx())

    def test_release_skill_renders_clean(self):
        out = self.render_asset("skills/release/SKILL.md")
        self.assertNotIn("{{", out)
        self.assertIn("demo-app", out)
        self.assertIn("version.py verify", out)
        self.assertTrue(out.startswith("---\n"))
        self.assertIn("v{version}", out)  # tag.format의 단일 중괄호는 보존된다
        self.assertLessEqual(len(out.splitlines()), 149)  # 마커 1줄 삽입 후 150줄 이하

    def test_release_skill_direct_push_tag_and_github_sections(self):
        out = self.render_asset("skills/release/SKILL.md")
        self.assertIn("git push origin main", out)
        self.assertIn("git tag -a", out)
        self.assertIn("gh release create", out)
        self.assertIn("chore(release): {version}", out)

    def test_release_skill_omits_github_when_disabled(self):
        ctx = base_ctx(github={"release": False, "generateNotes": False,
                               "releaseYml": False})
        out = self.render_asset("skills/release/SKILL.md", ctx)
        self.assertNotIn("gh release create", out)
        self.assertNotIn("gh auth status", out)

    def test_release_skill_post_release_none(self):
        ctx = base_ctx()
        ctx["scope"]["postRelease"]["bump"] = "none"
        out = self.render_asset("skills/release/SKILL.md", ctx)
        self.assertIn("post-release bump 없음", out)
        self.assertNotIn("--qualifier SNAPSHOT", out)

    def test_release_skill_warns_on_ci_tag_trigger(self):
        ctx = base_ctx()
        ctx["repo"]["tagTriggersDeployment"] = True
        out = self.render_asset("skills/release/SKILL.md", ctx)
        self.assertIn("배포를 트리거", out)

    def test_release_skill_signed_tag(self):
        ctx = base_ctx()
        ctx["scope"]["tag"]["signed"] = True
        out = self.render_asset("skills/release/SKILL.md", ctx)
        self.assertIn("git tag -s", out)
        self.assertNotIn("git tag -a", out)
        # signed=false (default) still uses annotated -a:
        self.assertIn("git tag -a", self.render_asset("skills/release/SKILL.md"))

    def test_release_notes_skill_renders_clean(self):
        out = self.render_asset("skills/release-notes/SKILL.md")
        self.assertNotIn("{{", out)
        self.assertIn("PR 메타데이터가 1차 소스", out)  # mergePolicy=squash 기본
        self.assertLessEqual(len(out.splitlines()), 149)


class FullRenderTest(unittest.TestCase):
    def test_real_assets_render_end_to_end(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "demo-app"
            repo.mkdir()
            cfg = scope_config(
                [{"file": "gradle.properties", "type": "properties-key", "key": "version"}])
            write(repo / ".superrelease" / "config.json",
                  json.dumps(cfg, ensure_ascii=False, indent=2))
            write(repo / "gradle.properties", "version=0.1.0\n")
            r = run_script(PLUGIN_SCRIPTS / "render.py",
                           "--config", repo / ".superrelease" / "config.json",
                           "--assets", ASSETS, "--repo", repo)
            self.assertEqual(r.returncode, 0, r.stderr)
            for rel in (".claude/skills/release/SKILL.md",
                        ".claude/skills/release-notes/SKILL.md",
                        ".superrelease/scripts/version.py",
                        ".superrelease/scripts/next-version.py",
                        ".superrelease/templates/notes-single.md",
                        ".superrelease/templates/changelog-entry.md",
                        ".github/release.yml"):
                self.assertTrue((repo / rel).is_file(), rel + " missing")
            skill = (repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
            self.assertIn("generated by superrelease v0.1.0", skill)
            verify = run_script(repo / ".superrelease" / "scripts" / "version.py", "verify")
            self.assertEqual(verify.returncode, 0, verify.stderr)


class MonorepoAssetsTest(unittest.TestCase):
    def render_asset(self, rel, ctx=None):
        text = (ASSETS / rel).read_text(encoding="utf-8")
        return render.render_template(text, ctx or mono_ctx())

    def test_release_monorepo_renders_clean(self):
        out = self.render_asset("skills/release-monorepo/SKILL.md")
        self.assertNotIn("{{", out)
        self.assertIn("demo-mono", out)
        self.assertIn("changed-packages.py", out)
        self.assertIn("--scope", out)
        self.assertIn("dependents", out)
        self.assertIn("네임스페이스", out)
        self.assertTrue(out.startswith("---\n"))
        self.assertLessEqual(len(out.splitlines()), 149)

    def test_release_monorepo_no_scope_inlining(self):
        # scope별 값(태그 포맷, 수식어 등)은 인라인 금지 — a@ 같은 특정 scope 값이 없어야 한다
        out = self.render_asset("skills/release-monorepo/SKILL.md")
        self.assertNotIn("a@{version}", out)
        self.assertIn("chore(release): {scope}@{version}", out)  # repo 수준 값은 인라인

    def test_release_monorepo_omits_github_when_disabled(self):
        ctx = mono_ctx(github={"release": False, "generateNotes": False,
                               "releaseYml": False})
        out = self.render_asset("skills/release-monorepo/SKILL.md", ctx)
        self.assertNotIn("gh release create", out)
        self.assertNotIn("gh auth status", out)

    def test_release_notes_monorepo_renders_clean(self):
        out = self.render_asset("skills/release-notes-monorepo/SKILL.md")
        self.assertNotIn("{{", out)
        self.assertIn("changed-packages.py", out)
        self.assertIn("notes-package.md", out)
        self.assertLessEqual(len(out.splitlines()), 149)

    def test_notes_package_language_blocks(self):
        ko = self.render_asset("templates/notes-package.md")
        self.assertIn("하이라이트", ko)
        self.assertNotIn("Highlights", ko)
        ctx = mono_ctx()
        ctx["scope"]["notes"]["language"] = "en"
        en = self.render_asset("templates/notes-package.md", ctx)
        self.assertIn("Highlights", en)
        self.assertNotIn("하이라이트", en)
        ctx["scope"]["notes"]["language"] = "both"
        both = self.render_asset("templates/notes-package.md", ctx)
        self.assertIn("하이라이트", both)
        self.assertIn("Highlights", both)


class FullRenderMonorepoTest(unittest.TestCase):
    def test_monorepo_render_end_to_end(self):
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp) / "demo-mono"
            repo.mkdir()
            write(repo / ".superrelease" / "config.json",
                  json.dumps(monorepo_config(), ensure_ascii=False, indent=2))
            write(repo / "packages" / "a" / "package.json",
                  '{\n  "name": "a",\n  "version": "0.1.0"\n}\n')
            write(repo / "packages" / "b" / "package.json",
                  '{\n  "name": "b",\n  "version": "0.1.0"\n}\n')
            r = run_script(PLUGIN_SCRIPTS / "render.py",
                           "--config", repo / ".superrelease" / "config.json",
                           "--assets", ASSETS, "--repo", repo)
            self.assertEqual(r.returncode, 0, r.stderr)
            skill = (repo / ".claude/skills/release/SKILL.md").read_text(encoding="utf-8")
            self.assertIn("모노레포", skill)
            self.assertIn("changed-packages.py", skill)
            notes_skill = (repo / ".claude/skills/release-notes/SKILL.md").read_text(encoding="utf-8")
            self.assertIn("changed-packages.py", notes_skill)
            self.assertTrue((repo / ".superrelease/scripts/changed-packages.py").is_file())
            self.assertTrue((repo / ".superrelease/templates/notes-package.md").is_file())
            self.assertFalse((repo / ".superrelease/templates/notes-single.md").exists())
            verify = run_script(repo / ".superrelease" / "scripts" / "version.py", "verify")
            self.assertEqual(verify.returncode, 0, verify.stderr)


if __name__ == "__main__":
    unittest.main()
